### ISSUE TITLE
刚看了一下你关于线段的划分，方法应该是有问题的

### ISSUE THREAD

**Issue by g-guo123456** [zengbin93/czsc#14]
刚看了一下关于线段的划分，主要是去除前后顶/底的情况，按照笔划分后，就不应该再有这种笔存在了。缠论中，线段的划分主要是使用特征序列方法，对线段进行确认，涉及有缺口和没有缺口的不同工况，所以，感觉线段划分方法似乎有些问题

**Comment by zengbin93** [comment]
@g-guo123456 线段的识别没有严格按定义来，我按照自己的理解实现的，准确率在90%以上，这里有跟原文的对比 https://www.jianshu.com/p/b2c60596528a

**Comment by g-guo123456** [comment]
我看到了这个对比，看上去是比较一致的，其中的奥妙看来还需要逐步的去体会。此外，想问下，这个绘图是怎么做到的，如何在图上，或者分析软件中，将识别出的线段程序化的标注上去
