### ISSUE TITLE
支持从csv里面直接读取股票信息

### ISSUE THREAD

**Issue by fengyqy** [zengbin93/czsc#19]
现在的get_kline是从Tushare上获取的，对于一些不方便访问服务器的（比如：离线研究），可以支持get_kline_from_csv会好一些，我试着添加了一下，但是比较死板:(，如果你的代码也可以支持就更好了，谢谢

**Comment by zengbin93** [comment]
@fengyqy 读取csv的K线是可以的，你只要根据你的K线写一个格式化函数就好。具体的格式：
![image](https://user-images.githubusercontent.com/24988472/97934389-85bae600-1db0-11eb-8eb5-afbadcde3533.png)

**Comment by fengyqy** [comment]
我是读离线文件，但是我的日K线各种，就是dt那列是，2020-01-07，下一个是2020-01-08这种，但是，最后出错。
