### ISSUE TITLE
你好，关于分型的设定

### ISSUE THREAD

**Issue by zjin42** [zengbin93/czsc#2]
你好，我仔细看了一下你网址中的分型结果。发现很多分型部分有分型共用K线的问题。

按定义，顶底分型中间至少有一个K线。

请问这个地方你有留意吗？

**Comment by zengbin93** [comment]
应该没有这个情况吧，我这里识别分型是严格按照定义来的。方便的话，你把图发出来看看，确认一下。 @zjin42

**Comment by zjin42** [comment]
不好意思，我把分型划分结果看成笔的划分结果了。分型划分有共用k线情况，笔的分型并没有。是我看错了。

你划分后实战应用了吗？效果怎么样？

**Comment by zjin42** [comment]
想咨询一下你这个在线k线分析网站，是用什么做的？感觉十分酷炫 ：）
