### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by adamwuyu** [zengbin93/czsc#27]
此文件发现两处错误：
https://github.com/zengbin93/czsc/blob/master/examples/pyecharts%20%E5%8F%AF%E8%A7%86%E5%8C%96%E5%88%86%E6%9E%90%E7%BB%93%E6%9E%9C.ipynb
1 ka_1m定义中`name=freq_map.get(freq, "本级别"), bi_mode="new", `与前面重复，报错了。删除即可；
2 KlineAnalyze初始化函数中没有max_xd_len函数，应该怎么处理？

**Comment by fialaux** [comment]
第二个问题我试了下把max_xd_len=20删掉就可以运行了，但不知道会有什么影响
