### ISSUE TITLE
关于笔的确认问题

### ISSUE THREAD

**Issue by y1281010069** [zengbin93/czsc#38]
假设有一个顶分型 ，后面接一个底分型，但是 两个分型之间的不足7跟，会触发一个问题，
如果第二个底分型的最低点比前面那个底分型的低点高，第二个底分型是选不中的，因为前面的代码要求选出最低的底分型
后面就可能触发破坏两笔

如下图是做了包含处理之后，按逻辑可能选出来的是 蓝色线，期望是 红色线
fxb 可不可以选出一个备用的，如果  两个分型之间的不足7跟，就用这个备用的来
![image](https://user-images.githubusercontent.com/12521372/111861548-1f62e880-898a-11eb-9a90-0756abf39931.png)

**Comment by zengbin93** [comment]
@y1281010069 笔的顶底分型严格要求是最高最低点，对于后面的走势分解非常关键。按我的理解，蓝线作为笔划分是没问题的

**Comment by y1281010069** [comment]
确实，翻看了禅师的原文，在问答里面有提到 ，顶和底一定是一笔的最高最低，第三个红箭头笔违反了这个规则
第二个红箭头笔顶不算的话，那就是蓝线作为笔划分是正确的
