### ISSUE TITLE
使用该方法进行可视化之后发现某些笔的顶分型选择了candle的low，某些底分型选择了candle的high。

### ISSUE THREAD

**Issue by liujt14** [zengbin93/czsc#6]
![image](https://user-images.githubusercontent.com/32155003/74608649-00a67880-511e-11ea-9c60-838b8ecac444.png)

**Comment by zengbin93** [comment]
@liujt14 你这个情况应该是画图错误。请参考这个项目的实现：https://github.com/zengbin93/gm_chan
