### ISSUE TITLE
笔标记出现错误 & 能否添加笔和段的连线

### ISSUE THREAD

**Issue by liuyijian** [zengbin93/czsc#7]
<img width="1322" alt="1" src="https://user-images.githubusercontent.com/28282800/74920056-7f453380-5406-11ea-9dff-48dc69f6f471.png">

**Comment by zengbin93** [comment]
@liuyijian 你这个K线有重复吧，我跑出来的结果不会有这个情况。从来没遇到过

**Comment by zengbin93** [comment]
@liuyijian 添加连线会让整张图看起来比较杂乱，直接看标记就够了

**Comment by liuyijian** [comment]
建议参考echarts，这个K线图缩放有点难受

**Comment by liuyijian** [comment]
另外想请教一下这个三类买卖点的代码如何使用，有文档吗，谢谢
