### ISSUE TITLE
版本202003 线段 划分 错误

### ISSUE THREAD

**Issue by word911** [zengbin93/czsc#8]
上海A股603982，日线数据（20190522-20200306），基于全部日K线进行划分，使用KlineAnalyze函数，输出如下：

    print("线段：", ka.xd, "\n")
    print("中枢：", ka.zs, "\n")

线段： [{'dt': '2019-06-12', 'fx_mark': 'g', 'xd': 35.65}, {'dt': '2019-11-29', 'fx_mark': 'd', 'xd': 15.4}] 
中枢： [] 

由图知2019年11月29日之后，又出现低点（20200204），所以线段结束位置要发生变化。与线段输出不符。
特告知。感谢分享。

**Comment by zengbin93** [comment]
@word911 你好，这个线段识别是没有问题的。线段的定义并没有要求线段必须是最低点结束，满足定义即可。
